#!/usr/bin/env python3
"""
commit-msg hook - Validates conventional commit format.

This hook validates that commit messages follow the Conventional Commits
specification: https://www.conventionalcommits.org/

Valid formats:
  type: description
  type(scope): description
  type!: breaking change description
  type(scope)!: breaking change description

Valid types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert

Cross-platform compatible (Windows, macOS, Linux).
"""

import re
import subprocess
import sys
from pathlib import Path


# Exit codes for clarity and maintainability
EXIT_SUCCESS = 0
EXIT_FAILURE = 1
TITLE_MAX_LENGTH = 100
BODY_MAX_LINE_LENGTH = 120

# Valid commit types per Conventional Commits specification
VALID_TYPES = [
    "feat",
    "fix",
    "docs",
    "style",
    "refactor",
    "perf",
    "test",
    "build",
    "ci",
    "chore",
    "revert",
]

# Pattern for conventional commit format
# type: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
# optional scope in parentheses
# optional ! for breaking changes
# colon and space
# description
CONVENTIONAL_COMMIT_PATTERN = re.compile(
    r"^(" + "|".join(VALID_TYPES) + r")(\(.+\))?!?: [a-zA-Z].*"
)

# Preserve gitlint's default exemptions for non-merge messages generated by Git.
# Merge commits are identified from repository metadata instead of their title.
IGNORED_GIT_MESSAGE_PREFIXES = (
    'Revert "',
    "fixup! ",
    "amend! ",
    "squash! ",
)
SCISSORS_MARKER = "------------------------ >8 ------------------------"


def cleanup_commit_message(commit_msg: str, comment_char: str = "#") -> str:
    """Remove Git template comments and content below its scissors marker."""
    cleaned: list[str] = []
    for line in commit_msg.splitlines():
        stripped = line.lstrip()
        if stripped.startswith(f"{comment_char} {SCISSORS_MARKER}"):
            break
        if stripped.startswith(comment_char):
            continue
        cleaned.append(line)
    return "\n".join(cleaned)


def extract_subject(commit_message: str) -> str:
    """
    Extract the subject portion of a commit message.

    The subject is everything after 'type(scope): ' or 'type: '.

    Args:
        commit_message: Full commit message

    Returns:
        Subject portion of the message
    """
    # Split on first ': ' occurrence
    parts = commit_message.split(": ", 1)
    if len(parts) == 2:
        return parts[1].strip()
    return ""


def validate_subject_case(subject: str) -> tuple[bool, str]:
    """
    Validate that subject starts with lowercase letter.

    Matches commitlint rule: subject-case: [2, 'always', 'lower-case']

    Args:
        subject: The subject portion of commit message (after type/scope)

    Returns:
        Tuple of (is_valid, error_message)
    """
    if not subject:
        return False, "Subject is empty"

    first_char = subject[0]

    # Allow non-alphabetic first characters (numbers, special chars)
    if not first_char.isalpha():
        return True, ""

    # First alphabetic character must be lowercase
    if first_char.isupper():
        return False, f"subject must start with lowercase letter (found '{first_char}')"

    return True, ""


def validate_commit_text(
    commit_msg: str,
    author_name: str = "",
    *,
    is_merge_commit: bool = False,
) -> bool:
    """Validate one complete commit message without third-party dependencies."""
    lines = commit_msg.splitlines()
    first_line = lines[0].strip() if lines else ""

    if not first_line:
        print_error_message("", "Commit message is empty")
        return False

    if is_merge_commit or first_line.startswith(IGNORED_GIT_MESSAGE_PREFIXES):
        return True

    if len(first_line) > TITLE_MAX_LENGTH:
        print_error_message(
            first_line,
            f"Title exceeds {TITLE_MAX_LENGTH} characters",
        )
        return False

    if not CONVENTIONAL_COMMIT_PATTERN.fullmatch(first_line):
        print_error_message(first_line, "Does not follow Conventional Commits format")
        return False

    if author_name != "dependabot[bot]":
        for line_number, line in enumerate(lines[1:], start=2):
            if len(line) > BODY_MAX_LINE_LENGTH:
                print_error_message(
                    first_line,
                    f"Body line {line_number} exceeds {BODY_MAX_LINE_LENGTH} characters",
                )
                return False

    subject = extract_subject(first_line)
    is_valid, error_msg = validate_subject_case(subject)

    if not is_valid:
        print("")
        print(f"❌ COMMIT REJECTED - {error_msg}")
        print("")
        print("Your commit message:")
        print(f"  {first_line}")
        print("")
        print(
            "The subject must start with a lowercase letter to match CI/CD requirements."
        )
        print("")
        print("Examples:")
        print("  ✅ feat: add user authentication")
        print("  ✅ fix: resolve timeout issue")
        print("  ❌ feat: Add user authentication  (uppercase 'A')")
        print("  ❌ fix: Resolve timeout issue     (uppercase 'R')")
        print("")
        return False

    return True


def validate_commit_message(commit_msg_file: Path) -> bool:
    """
    Validate that the commit message follows Conventional Commits format.

    Args:
        commit_msg_file: Path to the file containing the commit message

    Returns:
        True if valid, False otherwise
    """
    try:
        commit_msg = commit_msg_file.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        print(f"ERROR: Could not read commit message file: {e}", file=sys.stderr)
        return False

    merge_in_progress = (
        subprocess.run(
            ["git", "rev-parse", "--quiet", "--verify", "MERGE_HEAD"],
            capture_output=True,
            timeout=10,
        ).returncode
        == 0
    )
    comment_char_result = subprocess.run(
        ["git", "config", "--get", "core.commentChar"],
        capture_output=True,
        text=True,
        timeout=10,
    )
    configured_comment_char = comment_char_result.stdout.strip()
    comment_char = (
        configured_comment_char
        if comment_char_result.returncode == 0 and configured_comment_char != "auto"
        else "#"
    )
    return validate_commit_text(
        cleanup_commit_message(commit_msg, comment_char),
        is_merge_commit=merge_in_progress,
    )


def validate_git_commits(revision: str, *, is_range: bool) -> bool:
    """Validate one Git commit or every commit in a revision range."""
    command = (
        ["git", "rev-list", "--reverse", revision]
        if is_range
        else ["git", "rev-parse", revision]
    )
    try:
        resolved = subprocess.run(
            command,
            check=True,
            capture_output=True,
            text=True,
            timeout=10,
        ).stdout.splitlines()
    except (
        FileNotFoundError,
        subprocess.CalledProcessError,
        subprocess.TimeoutExpired,
    ) as error:
        print(
            f"ERROR: Could not resolve Git revision {revision}: {error}",
            file=sys.stderr,
        )
        return False

    if not resolved:
        print(f"ERROR: Git revision contains no commits: {revision}", file=sys.stderr)
        return False

    valid = True
    for commit_sha in resolved:
        try:
            metadata = subprocess.run(
                ["git", "show", "-s", "--format=%P%x00%an%x00%B", commit_sha],
                check=True,
                capture_output=True,
                text=True,
                timeout=10,
            ).stdout
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as error:
            print(
                f"ERROR: Could not read commit {commit_sha}: {error}", file=sys.stderr
            )
            return False
        parents, author_name, message = metadata.split("\0", maxsplit=2)
        if not validate_commit_text(
            message,
            author_name.rstrip("\n"),
            is_merge_commit=len(parents.split()) > 1,
        ):
            print(f"Rejected commit: {commit_sha}", file=sys.stderr)
            valid = False
    return valid


def print_error_message(commit_msg: str, reason: str) -> None:
    """Print a helpful error message for invalid commit messages."""
    print("")
    print("ERROR: Commit message does not follow Conventional Commits format.")
    print("")
    print("Your commit message:")
    print(f"  {commit_msg}")
    print("")
    print("Expected format:")
    print("  type(scope): description")
    print("")
    print(f"Valid types: {', '.join(VALID_TYPES)}")
    print("")
    print("Examples:")
    print("  feat: add user dashboard")
    print("  fix(auth): resolve login timeout")
    print("  feat!: redesign API endpoints (breaking change)")
    print("  refactor(api)!: remove deprecated endpoints")
    print("")
    print("See: https://www.conventionalcommits.org/")
    print("")


def main() -> int:
    """
    Main entry point for commit-msg hook.

    Returns:
        EXIT_SUCCESS (0) on success, EXIT_FAILURE (1) on failure
    """
    if len(sys.argv) == 3 and sys.argv[1] in {"--commit", "--commits"}:
        valid = validate_git_commits(sys.argv[2], is_range=sys.argv[1] == "--commits")
        return EXIT_SUCCESS if valid else EXIT_FAILURE

    if len(sys.argv) != 2:
        print(
            "Usage: commit_msg.py <message-file> | --commit <revision> | --commits <range>",
            file=sys.stderr,
        )
        return EXIT_FAILURE

    commit_msg_file = Path(sys.argv[1])

    if not commit_msg_file.exists():
        print(
            f"ERROR: Commit message file not found: {commit_msg_file}", file=sys.stderr
        )
        return EXIT_FAILURE

    if validate_commit_message(commit_msg_file):
        return EXIT_SUCCESS
    return EXIT_FAILURE


if __name__ == "__main__":
    sys.exit(main())
